/** @file */

#include <key_codes.h>

/** Sorted from the most likely most often pressed key to least likely least often. The priority has been determined by nearly <b>2 000 000</b> registered keypresses throughout weeks of recording. */
const unsigned short keys_pqueue[104] = {
KEY_LMB,    ///< Highest priority to be checked
KEY_RMB,    ///< Slightly lower priority to be checked, still second highest
KEY_SPACE,  ///< 3rd highest priority to be checked
KEY_A,      ///< 4th highest priority to be checked
KEY_E,      ///< . . .
KEY_O,
KEY_I,
KEY_BACK,
KEY_RETURN,
KEY_T,
KEY_Z,
KEY_N,
KEY_S,
KEY_C,
KEY_L,
KEY_R,
KEY_M,
KEY_D,
KEY_SHIFT,
KEY_W,
KEY_Y,
KEY_K,
KEY_CTRL,
KEY_P,
KEY_J,
KEY_U,
KEY_B,
KEY_G,
KEY_RIGHT,
KEY_DOWN,
KEY_H,
KEY_TAB,
KEY_ALT,
KEY_F,
KEY_X,
KEY_V,
KEY_1,
KEY_PLUS,
KEY_LEFT,
KEY_SLASH,
KEY_2,
KEY_COMMA,
KEY_DOT,
KEY_MINUS,
KEY_3,
KEY_9,
KEY_4,
KEY_UP,
KEY_5,
KEY_8,
KEY_6,
KEY_ESC,
KEY_SEMICLN,
KEY_QUOTE,
KEY_LBRACKET,
KEY_RBRACKET,
KEY_7,
KEY_Q,
KEY_DEL,
KEY_TILDE,
KEY_CAPSLOCK,
KEY_F5,
KEY_DIVIDE,
KEY_DECIMAL,
KEY_PGUP,
KEY_PGDN,
KEY_F4,
KEY_NUMPAD0,
KEY_NUMPAD8,
KEY_NUMPAD7,
KEY_NUMPAD9,
KEY_NUMPAD3,
KEY_NUMPAD1,
KEY_NUMPAD4,
KEY_F11,
KEY_F12,
KEY_NUMPAD5,
KEY_INS,
KEY_F9,
KEY_NUMPAD2,
KEY_NUMPAD6,
KEY_NUMPAD5,
KEY_F1,
KEY_F2,
KEY_F6,
KEY_F3,
KEY_F7,
KEY_F8,
KEY_F10,
KEY_MMB,
KEY_END,
KEY_HOME,
KEY_PSCRN,
KEY_LWIN,
KEY_RWIN,
KEY_APPS,
KEY_MULTIPLY,
KEY_ADD,
KEY_SEPARATOR,
KEY_SUBTRACT,
KEY_DECIMAL,
KEY_NUMLCK,
KEY_SCLLCK, ///< Second lowest priority to be checked
KEY_LINE,   ///< Lowest priority to be checked
};

/** Determines the size of keys priority queue. */
const int keys_pqueue_size = sizeof(keys_pqueue) / sizeof(keys_pqueue[0]);
